export const ROUTES = {
    home:           "/",
    login:          "/login",
    register:       "/register",
    ownerRegister:  "/owner",
    ownerReview:    "/owner/review",
    pitch:          "/pitch",
    leagues:        "/leagues",
    book:           "/book",
    booking:        "/booking",
    ownerDashboard: "/owner/dashboard",
    ownerPitches:   "/owner/pitches",
    ownerCustomers: "/owner/customers",
    ownerAnalytics: "/owner/analytics",
    community:      "/community",
    bookingSuccess: "/booking/success",
    checkout:       "/checkout",
    adminDashboard: "/admin",
    profile:        "/profile",
}