import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { StoreProvider } from '@/store/StoreProvider';
import { GoogleIdentityProvider } from '@/features/auth/components/googleIdentityProvider';
import { Providers } from '@/components/providers';
import AuthInitializer from '@/components/auth/AuthInitializer';
import { FloatingChatWidget } from '@/features/chatbox/components/ai-chat/FloatingChatWidget';
import { Toaster } from 'sonner';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <StoreProvider>
          <AuthInitializer>
            <Providers>
              <GoogleIdentityProvider>
                {children}
                <FloatingChatWidget />
                <Toaster richColors position="top-right" />
              </GoogleIdentityProvider>
            </Providers>
          </AuthInitializer>
        </StoreProvider>
      </body>
    </html>
  );
}
